// constants/medicalServices.js
import {
  Heart,
  Users,
  Activity,
  Shield,
  Stethoscope,
  PawPrint,
  Leaf,
  Brain,
  Cross,
  Droplets,
  Baby,
  Utensils,
  Sparkles,
  UserCheck,
  Ambulance,
  Video,
  TestTube,
} from "lucide-react";

export const medicalServices = [
  {
    icon: Ambulance,
    title: "Emergency",
    desc: "Immediate medical transport with trained paramedics",
    color: "from-red-500 to-rose-500",
    bgColor: "bg-red-50",
    buttonText: "Book Now",
    badge: "24/7 Available",
  },
  {
    icon: UserCheck,
    title: "Doctor at Home",
    desc: "Qualified doctors available for home visits",
    color: "from-blue-500 to-cyan-500",
    bgColor: "bg-blue-50",
    buttonText: "Schedule Visit",
    badge: "Same Day",
  },
  {
    icon: Video,
    title: "Video Consultation",
    desc: "Consult specialists from the comfort of your home",
    color: "from-green-500 to-emerald-500",
    bgColor: "bg-green-50",
    buttonText: "Start Consultation",
    badge: "Instant",
  },
  {
    icon: TestTube,
    title: "Home Diagnostics",
    desc: "Sample collection and lab tests at your location",
    color: "from-purple-500 to-violet-500",
    bgColor: "bg-purple-50",
    buttonText: "Book Tests",
    badge: "Free Collection",
  },
  {
    icon: Heart,
    title: "Care Match",
    desc: "Personalized care coordination for you and your family",
    color: "from-pink-500 to-rose-500",
    bgColor: "bg-pink-50",
    buttonText: "Explore Now",
    badge: "Coming Soon",
  },
  {
    icon: Cross,
    title: "AidFirst",
    desc: "First aid and emergency response training",
    color: "from-red-500 to-rose-500",
    bgColor: "bg-red-50",
    buttonText: "Learn More",
    badge: "Coming Soon",
  },
  {
    icon: Users,
    title: "Coach Match",
    desc: "Connect with expert health coaches for your needs",
    color: "from-blue-500 to-cyan-500",
    bgColor: "bg-blue-50",
    buttonText: "Find a Coach",
    badge: "Coming Soon",
  },
  {
    icon: Activity,
    title: "Health Buddy",
    desc: "Daily wellness tracking and health support",
    color: "from-green-500 to-emerald-500",
    bgColor: "bg-green-50",
    buttonText: "Get Started",
    badge: "Coming Soon",
  },
  {
    icon: Shield,
    title: "Immuni Care",
    desc: "Vaccination and immunity-boosting services",
    color: "from-purple-500 to-violet-500",
    bgColor: "bg-purple-50",
    buttonText: "Learn More",
    badge: "Coming Soon",
  },
  {
    icon: Stethoscope,
    title: "MedEquip",
    desc: "Medical equipment rentals and supplies",
    color: "from-indigo-500 to-blue-500",
    bgColor: "bg-indigo-50",
    buttonText: "Explore Equipment",
    badge: "Coming Soon",
  },
  {
    icon: PawPrint,
    title: "PetWell",
    desc: "Trusted health services for your furry friends",
    color: "from-orange-500 to-amber-500",
    bgColor: "bg-orange-50",
    buttonText: "Explore Pet Care",
    badge: "Vet Approved",
  },
  {
    icon: Leaf,
    title: "AyurCare",
    desc: "Ayurvedic treatments and wellness solutions",
    color: "from-teal-500 to-green-500",
    bgColor: "bg-teal-50",
    buttonText: "Discover Now",
    badge: "Coming Soon",
  },
  {
    icon: Brain,
    title: "Mental Health",
    desc: "Support for mental wellness and therapy",
    color: "from-rose-500 to-pink-500",
    bgColor: "bg-rose-50",
    buttonText: "Get Support",
    badge: "Coming Soon",
  },
  {
    icon: Droplets,
    title: "Social Wall",
    desc: "Blood donation and transfusion services",
    color: "from-red-600 to-red-500",
    bgColor: "bg-red-50",
    buttonText: "Join Now",
    badge: "Coming Soon",
  },
  {
    icon: Baby,
    title: "ChildCare++",
    desc: "Pediatric care and child health services",
    color: "from-yellow-500 to-orange-500",
    bgColor: "bg-yellow-50",
    buttonText: "Explore Care",
    badge: "Coming Soon",
  },
  {
    icon: Utensils,
    title: "NutritiGuide",
    desc: "Nutrition planning and dietary guidance",
    color: "from-lime-500 to-green-500",
    bgColor: "bg-lime-50",
    buttonText: "Plan Your Diet",
    badge: "Coming Soon",
  },
  {
    icon: Sparkles,
    title: "DermaCare",
    desc: "Dermatology and skin care solutions",
    color: "from-violet-500 to-purple-500",
    bgColor: "bg-violet-50",
    buttonText: "Book Now",
    badge: "Coming Soon",
  },
];